name: ManagedAgentsDemo

on:
  push:
    branches:
      - main
  pull_request:

env:
  NODE_OPTIONS: '--max_old_space_size=4096'

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 240
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '20'
      - run: yarn install --frozen-lockfile
      - name: Run verification
        run: 'npx nx affected -t export test lint --parallel 1 --no-cloud && npx nx affected -t e2e-ci --parallel 1 --no-cloud'
      - name: Tag main branch if all jobs succeed
        uses: nrwl/nx-tag-successful-ci-run@v1

  pr:
    runs-on: ubuntu-latest
    timeout-minutes: 240
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '20'
      - name: Start CI run
        run: 'npx nx-cloud start-ci-run --distributes-on="15 linux-medium-plus-js" --stop-agents-after="e2e-ci"'
      - run: yarn install --frozen-lockfile
      - name: Run verification
        run: 'npx nx run-many -t export test lint --parallel 1 && npx nx run-many -t e2e-ci --parallel 1'
